### PR TITLE
Add GH version tag to docker image tagging

### PR DESCRIPTION
**Pull request by msschl**
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.

- Closes pelias/pelias#905
- Closes https://github.com/pelias/docker/issues/212

### CODE REVIEW

**Comment by missinglink** [comment]
I think we might be able to simplify this to a single command:

```bash
git tag --points-at $REVISION
```

That will return a list of tags which point to the current commit.
I guess it's possible that there is more than one, although in reality that will be rare.

**Comment by missinglink** [comment]
Yeah that looks good, since and simple 😃 

```bash
for tag in "$(git tag --points-at $REVISION)"; do
  tags+=("$DOCKER_PROJECT:$tag")
done
```

**Comment by missinglink** [comment]
Do we possibly need to pull the tags from the remote before doing this or will git have them locally when the repo is cloned?

**Comment by msschl** [comment]
I don't think so, as [git clone](https://git-scm.com/docs/git-clone) has an option to exclude tags i.e., `--no-tags`

**Review by orangejulius — APPROVED** [review]
Okay, I tested this out by copying the script locally (and commenting out the `docker push` lines 😁 )

It looks like for the (somewhat common) case where there's no tag for the current revision, a bit of error handling was needed. I pushed one commit to do this and so i think this is good to go.

**Comment by orangejulius** [comment]
Ah, of course! There will be another change required for this to work. Right now all our GitHub workflows run the unit tests, build docker images, and then publish a release.

So that means the release tag isn't generated until after we build the docker images 🤦.

I think we can easily swap the order around, we just have to do it everywhere :)

**Comment by orangejulius** [comment]
I re-ran one of our recent releases and there's yet one more little snag: as @missinglink feared GitHub Actions does not fetch tags by default: https://github.com/pelias/api/runs/2788185703?check_suite_focus=true#step:2:40

**Comment by orangejulius** [comment]
I added some code to fetch git tags (https://github.com/pelias/ci-tools/commit/a8d020f8bbcaf86552a9ea8870854a726c24475e), and after a CI run we now have a Docker image for the latest Pelias API version: https://hub.docker.com/layers/pelias/api/v5.26.1/images/sha256-b89b0da0e10ef5f242347b3e3b46c8916e731c006647b7607a58caff89f8cd2c?context=explore

We'll still want to work on re-ordering our CI components to make sure this works going forward, but all the pieces look to be in place overall.

**Comment by msschl** [comment]
That sounds good 🚀 Thank you very much 👍🏽

**Pull request merged**
